### ISSUE TITLE
Multiple pages mention only universe_wgsi.ini not config.ini

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/galaxy-site#16]
Many of the documentation pages still refer to the legacy configuration filename universe_wgsi.ini rather than the new name of config/galaxy.ini

Problem pages include:

https://wiki.galaxyproject.org/Learn/SecurityFeatures
https://wiki.galaxyproject.org/Admin/DiskQuotas
https://wiki.galaxyproject.org/Admin/SampleTracking/Demo
https://wiki.galaxyproject.org/Admin/Tools/MultipleOutputFiles
https://wiki.galaxyproject.org/Admin/Config/GenomeSpace
https://wiki.galaxyproject.org/Admin/Config/ApacheExternalUserAuth
https://wiki.galaxyproject.org/VisualizationSetup
https://wiki.galaxyproject.org/ToolShedApi

Other pages would benefit from minor edits to at least put the old form second and in brackets:

https://wiki.galaxyproject.org/Admin/Config/Performance/Cluster
https://wiki.galaxyproject.org/Admin/Interface
https://wiki.galaxyproject.org/ToolShed/InstallingRepositoriesToGalaxy
Some pages look fine, e.g.

https://wiki.galaxyproject.org/ToolShed/InstallingAndCompilingPackages

Or are clearly dated and appropriate for the time, e.g. Dev news briefs

https://wiki.galaxyproject.org/DevNewsBriefs/2010_07_16

This means lots of pages with the term which are fine:

https://wiki.galaxyproject.org/Admin/Tools/ToolConfigSyntax?action=fullsearch&titlesearch=0&from=0&value=universe_wsgi.ini

Originally raised on the mailing list here: https://lists.galaxyproject.org/pipermail/galaxy-dev/2016-November/025154.html

**Comment by dannon** [comment]
Should be fixed in https://github.com/galaxyproject/galaxy-site/pull/18

**Comment by peterjc** [comment]
Two further suggested noted on #18, but other than that this looks good. I have not grep'ed the new repository which would be the easy way to check the only remaining pages are valid historical ones like the news briefs.

**Comment by dannon** [comment]
Thanks @peterjc, done in #20.
