### ISSUE TITLE
Missing creole pages

### ISSUE THREAD

**Issue by dannon** [galaxyproject/galaxy-site#19]
There are some missing creole-based pages that need to be merged in.

**Comment by dannon** [comment]
https://wiki.galaxyproject.org/Admin/Interface?action=raw is one example

**Comment by tnabtaf** [comment]
Here's the complete list of remaining untranslated pages.

[runMigrationCreoleOnlyLog.txt](https://github.com/galaxyproject/galaxy-site/files/622430/runMigrationCreoleOnlyLog.txt)

I did not create a way to automatically translate from Creole to Moin or Markdown.

**Comment by dannon** [comment]
@tnabtaf Ok, I'll look at a way to do this today.

**Comment by tnabtaf** [comment]
Manually updating pages is a viable option.  It took me 5-15 minutes, depending on size, to manually convert a Creole page to Moin (might have done 30 pages or so).  We could just throw this list out there as a list of pages that need manual conversion.

**Comment by dannon** [comment]
@tnabtaf I found a ruby gem converter, going to script it up and try that first.

**Comment by dannon** [comment]
Fixed in #22
