### ISSUE TITLE
What should we call this web site?

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/galaxy-site#31]
Hi All,

We needed to call the new site something in the [initial announcement](https://new.galaxyproject.org/GalaxyUpdates/2016_12/), so we did.  However, we'd like have community input on what to call the new site before we officially make the swap.

The old site was clearly a *wiki*.  The new site has wiki-like characteristics, but it's not a wiki and calling it that might be misleading.  Our goals for the new site are to support community curated Galaxy documentation *and* a much broader range of content then the original wiki and the name should reflect that.

Here are two ideas from the team to start the discussion:

*  **Commons**: Galaxy Community Commons, Galaxy Commons, Community Commons
   * It certainly is a "commons", but ...
   * Easy to confuse with recent NIH efforts.
   * That acronym is already taken.
* **Hub**: Galaxy Community Hub, Galaxy Hub, Community Hub
   * Name reflects the goal of the site.
   * Not obviously confused with other prominent resources (that I know of!)

Any suggestions, preferences or thoughts?

**Comment by dannon** [comment]
"Galaxy Community Hub"

**Comment by martenson** [comment]
from [twitter](https://twitter.com/galaxyproject/status/806165782564663296):

- galaxedia
- Encyclopaedia Galactica
- Galaxystars

**Comment by dannon** [comment]
xref #34

**Comment by friedue** [comment]
in the twitter spirit:

* universe or cosmos
* stellar docs
* active center

**Comment by martenson** [comment]
from twitter: help.usegalaxy.org

**Comment by dannon** [comment]
Hub is the clear winner, closing this.
